Mod support
SkinsRestorer/SkinsRestorerX pull request #1734
Opened 2024-07-26 17:44 UTC by AlexProgrammerDE

2024-08-21 19:11 UTC, xknat requested changes
See below

2024-08-21 19:11 UTC, xknat commented on modded/src/fabric/java/net/skinsrestorer/modded/fabric/SRModPlatformImpl.java
> +        // NO-OP
Is this still needed?

2024-08-21 19:11 UTC, xknat commented on modded/src/main/java/net/skinsrestorer/modded/logger/Slf4jLoggerImpl.java
> +            case SEVERE -> logger.error(message);
Should this not be logger.servere?

2024-08-21 19:11 UTC, xknat commented on modded/src/main/java/net/skinsrestorer/modded/logger/Slf4jLoggerImpl.java
> +        }
Same as above

2024-08-23 17:23 UTC, AlexProgrammerDE commented on modded/src/main/java/net/skinsrestorer/modded/logger/Slf4jLoggerImpl.java
> +            case SEVERE -> logger.error(message);
Nah, slf4j calls the method for severe level error

2024-08-23 17:24 UTC, AlexProgrammerDE commented on modded/src/fabric/java/net/skinsrestorer/modded/fabric/SRModPlatformImpl.java
> +        // NO-OP
yes, because it needs an impl on every platform, neoforge has an impl

2024-08-23 17:24 UTC, AlexProgrammerDE commented on modded/src/main/java/net/skinsrestorer/modded/logger/Slf4jLoggerImpl.java
> +        }
Same as above

2024-08-23 17:25 UTC, xknat approved these changes
lgtm

2024-08-23 17:25 UTC, merged