Improve factories
SkinsRestorer/SkinsRestorerX pull request #439
Opened 2021-03-08 09:11 UTC by AlexProgrammerDE

2021-03-08 11:07 UTC, xknat requested changes
As discussed in discord:

>also, i checked config.java
we did switch REMOUNT_PLAYER_ON_UPDATE 
so enablesremountentities should be disablesremountplayer & disablesremoun.exist should turn it to false

2021-03-08 11:07 UTC, xknat commented on src/main/java/net/skinsrestorer/bukkit/skinfactory/UniversalSkinFactory.java
> +        File fileEnableRemountEntities = new File("plugins" + File.separator + "SkinsRestorer" + File.separator + "enablesremountentities");
https://discord.com/channels/186794372468178944/815969158470697021/818415205099765802

2021-03-10 10:16 UTC, xknat approved these changes

2021-03-11 12:26 UTC, xknat requested changes
These changes will bring the current mc 1.16 custom world name issue to lower versions.
Something we would like to have fixed first before merging.

2021-03-11 12:29 UTC, AlexProgrammerDE commented on src/main/java/net/skinsrestorer/bukkit/skinfactory/OldSkinRefresher.java
> +                else if (environment == World.Environment.THE_END)
@xknat the bug is somewhere caused here.

2021-03-11 14:29 UTC, AlexProgrammerDE commented
Decided to be made for v14.1 instead.

2021-03-13 22:15 UTC, merged