Completely rewrite code to use Path instead of FIle
SkinsRestorer/SkinsRestorerX pull request #925
Opened 2022-04-07 13:27 UTC by AlexProgrammerDE

2022-04-07 13:31 UTC, AlexProgrammerDE commented
Also rewrites default config values. Will continue work when I have some more time.

2022-04-08 06:36 UTC, xknat requested changes

2022-04-08 06:36 UTC, xknat commented on shared/src/main/java/net/skinsrestorer/shared/storage/MySQL.java
> +                        "&maxPoolSize=10" +
move to config mysql.options

2022-04-08 06:36 UTC, xknat commented on shared/src/main/java/net/skinsrestorer/shared/storage/SkinStorage.java
> +            } catch (IOException e) {
Don't you want to make this stream?

2022-04-08 06:36 UTC, xknat commented on shared/src/main/java/net/skinsrestorer/shared/storage/SkinStorage.java
> +            } catch (IOException e) {
Don't you want to make this stream?

2022-04-08 06:59 UTC, xknat approved these changes
lgtm

2022-04-08 06:59 UTC, merged